name: Deploy for task

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Eleventy
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output html
          install_dependencies: true
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: 34.220.137.151
          username: ubuntu
          key: ${{ secrets.SECRET }}
          rm: true
          source: "DEPLOY/workflow/task"
          target: "/var/www/html"
