name: website deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy website to example.com
        uses: appleboy/scp-action@master
        env:
          HOST: 3.109.54.100
          USERNAME: ubuntu
          KEY: ${{ secrets.SECRET }}
        with:
          source: "DEPlOY/*"
          target: "/var/www/html"
          strip_components: 1
